// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDanIWbDKc7MdzEeUB5wzGuBaZjjcVyACU',
    appId: '1:208996576545:web:a092a2a9330bf348f02260',
    messagingSenderId: '208996576545',
    projectId: 'sdfghj-a498e',
    authDomain: 'sdfghj-a498e.firebaseapp.com',
    storageBucket: 'sdfghj-a498e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClU34tmnhFul1V1Qx4hMwVwlZo4871cuw',
    appId: '1:208996576545:android:d9855a6dddef9317f02260',
    messagingSenderId: '208996576545',
    projectId: 'sdfghj-a498e',
    storageBucket: 'sdfghj-a498e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCOOCdeUhIgesRAQExieYObm2rW6_cPY',
    appId: '1:208996576545:ios:f47c8fd39eadfdd7f02260',
    messagingSenderId: '208996576545',
    projectId: 'sdfghj-a498e',
    storageBucket: 'sdfghj-a498e.appspot.com',
    iosBundleId: 'com.example.opslagstavle3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYCOOCdeUhIgesRAQExieYObm2rW6_cPY',
    appId: '1:208996576545:ios:2715a02d25ceffe9f02260',
    messagingSenderId: '208996576545',
    projectId: 'sdfghj-a498e',
    storageBucket: 'sdfghj-a498e.appspot.com',
    iosBundleId: 'com.example.opslagstavle3.RunnerTests',
  );
}
